language: python
python:
  - 2.7

before_install:
    - sudo apt-get install cmake
    - sudo ./travis/install-libgit2.sh

install:
    - ./venv.sh
    - . .venv/bin/activate
    - python setup.py install

script:
    - cd tests
    - ./test.sh
