language: python
python:
  - 2.7

env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

before_install:
    - sudo apt-get install cmake
    - ./travis/install-libgit2.sh

install:
    - ./venv.sh
    - . .venv/bin/activate
    - python setup.py install

script:
    - cd tests
    - ./test.sh
